# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SidamaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('roasted_date', models.DateTimeField()),
                ('bean_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BeanQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Bean')),
            ],
        ),
        migrations.CreateModel(
            name='BeanRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Bean')),
            ],
        ),
        migrations.CreateModel(
            name='BeanTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Bean')),
            ],
        ),
        migrations.CreateModel(
            name='BeanVarietal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Bean')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('continent', models.CharField(blank=True, max_length=400)),
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('description', models.CharField(blank=True, max_length=50)),
                ('quality_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('roaster_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('varietal_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='beanvarietal',
            name='varietal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Varietal'),
        ),
        migrations.AddField(
            model_name='beantag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Tag'),
        ),
        migrations.AddField(
            model_name='beanregion',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Region'),
        ),
        migrations.AddField(
            model_name='beanquality',
            name='quality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Quality'),
        ),
        migrations.AddField(
            model_name='bean',
            name='roaster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SidamaApp.Roaster'),
        ),
    ]
